### ISSUE TITLE
Add Travis CI to avoid breaking everything :p

### ISSUE THREAD

**Issue by MoOx** [fonzie/fonzie#22]
I can't make the latest version works. I'm having an issue 

``` bash
MYPROJECT/node_modules/bower/node_modules/tmp/lib/tmp.js:260
  throw err;
        ^
Error: Failed to load bower.json for package : MYPROJECT/components
    at Package.loadManifest (MYPROJECT/node_modules/fonzie/lib/package.js:29:11)
    at new Package (MYPROJECT/node_modules/fonzie/lib/package.js:9:24)
    at MYPROJECT/node_modules/fonzie/lib/builder.js:78:18
    at Array.forEach (native)
    at EventEmitter.<anonymous> (MYPROJECT/node_modules/fonzie/lib/builder.js:73:23)
    at EventEmitter.emit (events.js:95:17)
    at emitOut (MYPROJECT/node_modules/bower/lib/commands/list.js:187:13)
    at null.<anonymous> (MYPROJECT/node_modules/bower/lib/commands/list.js:219:9)
    at EventEmitter.emit (events.js:98:17)
    at MYPROJECT/node_modules/bower/node_modules/async/lib/async.js:116:25
```

I try to run test to check if there are working & when I run `grunt` I got an jshint error

``` bash
❯ grunt
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:lib" (jshint) task
Linting lib/package.js...ERROR
[L4:C7] 'fs' is defined but never used.
var fs = require('fs-extra');

Warning: Task "jshint:lib" failed. Use --force to continue.

Aborted due to warnings.
```

So I try to run tests directly & event them are not working

``` bash
❯ grunt nodeunit
Running "nodeunit:files" (nodeunit) task
Testing builder_test.js.....F.
Fatal error: Cannot call method 'split' of undefined
```

Am I missing something today ? Am I drunk ?
If not, it can be nice to setup Travis CI so it can run jshint+tests for each push (mail notification if you break something). I can help with that since I've setup Travis on different projects.

PS: You can rename this issue !

**Comment by MoOx** [comment]
Closing due to inactivity.
